// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmNopBlJYtqrH5viI9Y0uGVpkcA10TPK4',
    appId: '1:721961424361:web:721cf916f651f14f87a778',
    messagingSenderId: '721961424361',
    projectId: 'arenahub-98b15',
    authDomain: 'arenahub-98b15.firebaseapp.com',
    storageBucket: 'arenahub-98b15.firebasestorage.app',
    measurementId: 'G-03CVEFW9H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDK1i7rJHBHZkANepvtG_628Hxtpz9ZYk',
    appId: '1:721961424361:android:0c3a6e2c76b912a787a778',
    messagingSenderId: '721961424361',
    projectId: 'arenahub-98b15',
    storageBucket: 'arenahub-98b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKV3Gz25ABfYpZErl37gHrUzslI3zcaw',
    appId: '1:721961424361:ios:58cd55d18ec2d7df87a778',
    messagingSenderId: '721961424361',
    projectId: 'arenahub-98b15',
    storageBucket: 'arenahub-98b15.firebasestorage.app',
    androidClientId: '721961424361-6vetooe0hsnknqjn9alcpvgbslsf7qgg.apps.googleusercontent.com',
    iosClientId: '721961424361-5qe1u50cb57e96riuldl09g30jus643q.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbookinglapangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKV3Gz25ABfYpZErl37gHrUzslI3zcaw',
    appId: '1:721961424361:ios:58cd55d18ec2d7df87a778',
    messagingSenderId: '721961424361',
    projectId: 'arenahub-98b15',
    storageBucket: 'arenahub-98b15.firebasestorage.app',
    androidClientId: '721961424361-6vetooe0hsnknqjn9alcpvgbslsf7qgg.apps.googleusercontent.com',
    iosClientId: '721961424361-5qe1u50cb57e96riuldl09g30jus643q.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbookinglapangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmNopBlJYtqrH5viI9Y0uGVpkcA10TPK4',
    appId: '1:721961424361:web:546f60f6ac2a5db387a778',
    messagingSenderId: '721961424361',
    projectId: 'arenahub-98b15',
    authDomain: 'arenahub-98b15.firebaseapp.com',
    storageBucket: 'arenahub-98b15.firebasestorage.app',
    measurementId: 'G-K9VS54MW4E',
  );

}